version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # These should match your Supabase Docker network settings
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-http://localhost:54321}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-your-anon-key}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN:-}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - supabase_network
    depends_on:
      - supabase  # This assumes your Supabase service is named 'supabase' in Docker
    restart: unless-stopped

networks:
  supabase_network:
    external: true  # This will use the existing network where Supabase is running
