[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.5.0"
  NPM_VERSION = "10.2.3"
  NEXT_PUBLIC_DEMO_MODE = "true"

# Demo mode production environment
[context.production.environment]
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_SUPABASE_URL = "https://demo.logistics.seftech.com"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "demo-anon-key-for-display-only"
  SUPABASE_SERVICE_ROLE_KEY = "demo-service-key-for-display-only"
  NEXT_PUBLIC_APP_URL = "https://seftech-logistics-demo.netlify.app"

# Demo mode for deploy previews
[context.deploy-preview.environment]
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_SUPABASE_URL = "https://demo.logistics.seftech.com"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "demo-anon-key-for-display-only"

# Demo mode specific redirect - must come before catch-all
[[redirects]]
  from = "/"
  to = "/demo-landing"
  status = 302

# Handle Next.js routes - this should be last to catch all unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to improve security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Demo mode headers
[[headers]]
  for = "/demo*"
  [headers.values]
    X-Demo-Mode = "true"
    X-Robots-Tag = "noindex, nofollow"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Performance optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"
